### one must change the format of the table" generated by the R script called "prepare for circle plots". I'm currently doing that in excel.
### for circle plots" the table must be in the following format:
#from 	to	thickness
#Amazon	Andes	170

library(qgraph)
setwd("C:\\Users\\Ruud\\Desktop\\R working Directory\\scripts fernanda\\LASTEST VERSIONS\\Ferns")
datq<-read.table("number_of_transitions.txt",sep = "\t", header = T)
pdf("transitions_network.pdf")
qgraph(datq)
dev.off()


