### one must change the format of the table" generated by the R script called "prepare for circle plots". I'm currently doing that in excel.
### for circle plots" the table must be in the following format:
#from 	to	thickness
#Amazon	Andes	170

library(qgraph)
setwd("C:\\Users\\Sidonie\\Dropbox\\Carvalho_et_al_Neotropical_biome_shifts\\Data_and_analyses\\Analyses\\final_Biogeobears_analyses\\ferns")
datq<-read.table("number_of_transitions.txt",sep = "\t", header = T)
pdf("transitions_network.pdf")
Edges=as.data.frame(datq)
labels=c("Amazon","Andes","Atlantic_forest","Caribe","Central_America","Dry_diagonal","Dry_north")
color=c("#099605","#898A88","#80F538","#50FAEF","#1900F7","#F58402","#F5F102")
#qgraph(Edges,esize=5,gray=TRUE, color=color, labels=labels,  node.width=1.5, edge.width=1.5, layout="spring",maximum=5.306)
qgraph(Edges,gray=TRUE, color=color, labels=labels, node.width=1.1, edge.width=1.3)
?qgraph
dev.off()


